# general settings
name: finetune_RealESRGANx4plus_teacher_student_degradation
model_type: RealESRGANModelStudent
scale: 4
num_gpu: auto
manual_seed: 0
use_distillation: True  # Enable teacher-student distillation

# USM the ground-truth
l1_gt_usm: True
percep_gt_usm: True
gan_gt_usm: False

high_order_degradation: False  # Use paired data from RealisticDegradationGenerator

# dataset and data loader settings
datasets:
  train:
    name: DIV2K
    type: RealESRGANPairedDataset
    dataroot_gt: /datasets/RealESRGAN_data/dataset/train
    dataroot_lq: /datasets/RealESRGAN_data/dataset/train
    meta_info: /home/namlh/DLEnhance_ImageQuality/datasets/RealESRGAN_data/meta_info/meta_info_moderate_sub_pair.txt
    io_backend:
      type: disk
    gt_size: 256
    use_hflip: True
    use_rot: False
    use_shuffle: true
    num_worker_per_gpu: 2
    batch_size_per_gpu: 4
    dataset_enlarge_ratio: 1
    prefetch_mode: ~
  val:
    name: validation
    type: PairedImageDataset
    dataroot_gt: /datasets/RealESRGAN_data/dataset/test/HR
    dataroot_lq: /datasets/RealESRGAN_data/dataset/test/LR_moderate
    io_backend:
      type: disk

# network structures
network_g:
  type: RRDBNet
  num_in_ch: 3
  num_out_ch: 3
  num_feat: 64  # Reduced for student
  num_block: 23  # Reduced for student
  num_grow_ch: 32  # Reduced for student

network_d:
  type: UNetDiscriminatorSN
  num_in_ch: 3
  num_feat: 64
  skip_connection: True

# path
path:
  pretrain_network_g: /home/namlh/DLEnhance_ImageQuality/Real-ESRGAN/experiments/finetune_RealESRGANx4plus_400k_pairdata_21000state/models/net_g_365000.pth
  param_key_g: params_ema
  strict_load_g: false
  pretrain_network_d: /home/namlh/DLEnhance_ImageQuality/Real-ESRGAN/experiments/finetune_RealESRGANx4plus_400k_pairdata_21000state/models/net_d_365000.pth
  strict_load_d: true
  resume_state: ~

# training settings
train:
  ema_decay: 0.999
  optim_g:
    type: Adam
    lr: !!float 1e-4
    weight_decay: 0
    betas: [0.9, 0.99]
  optim_d:
    type: Adam
    lr: !!float 1e-4
    weight_decay: 0
    betas: [0.9, 0.99]
  scheduler:
    type: MultiStepLR
    milestones: [600000]
    gamma: 0.5
  total_iter: 600000
  warmup_iter: -1
  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.5
    reduction: mean
  perceptual_opt:
    type: PerceptualLoss
    layer_weights:
      'conv1_2': 0.1
      'conv2_2': 0.1
      'conv3_4': 1
      'conv4_4': 1
      'conv5_4': 1
    vgg_type: vgg19
    use_input_norm: true
    perceptual_weight: !!float 1.2  # Increased for better NIQE
    style_weight: 0
    range_norm: false
    criterion: l1
  gan_opt:
    type: GANLoss
    gan_type: vanilla
    real_label_val: 1.0
    fake_label_val: 0.0
    loss_weight: !!float 1e-1
  distillation_opt:
    type: L1Loss
    loss_weight: 0.7
    reduction: mean
    target: teacher_output
  feature_distillation_opt:
    type: L1Loss
    layer_weights:
      'block_2': 0.3
      'block_4': 0.3
      'block_6': 0.2
    loss_weight: 0.5
    reduction: mean
  net_d_iters: 1
  net_d_init_iters: 0

# validation settings
val:
  val_freq: !!float 5e3
  save_img: True
  metrics:
    psnr:
      type: calculate_psnr
      crop_border: 4
      test_y_channel: false
    ssim:
      type: calculate_ssim
      crop_border: 4
      test_y_channel: false
    niqe:
      type: calculate_niqe
      crop_border: 4

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500