name: train_realesrgan_siamese
model_type: RealESRGANSiameseModel
num_gpu: 1
scale: 4
gt_size: 128

datasets:
  train:
    name: TrainSiamese
    type: PairedSiameseImageDataset
    dataroot_gt: /datasets/RealESRGAN_data/dataset/train/HR_sub
    dataroot_lq_a: /datasets/RealESRGAN_data/dataset/train/LR_light_sub
    dataroot_lq_b: /datasets/RealESRGAN_data/dataset/train/LR_moderate_sub
    io_backend:
      type: disk
    use_hflip: true
    use_rot: true
    
    use_shuffle: true
    num_worker_per_gpu: 4
    batch_size_per_gpu: 6
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

network_g:
  type: RRDBNetFeatOut
  num_in_ch: 3
  num_out_ch: 3
  scale: 4
  num_feat: 64
  num_block: 23
  num_grow_ch: 32
  return_intermediate: true 

network_d:
  type: UNetDiscriminatorSN
  num_in_ch: 3
  num_feat: 64

path:
  pretrain_network_g: ~
  param_key_g: params_ema
  strict_load_g: true
  resume_state: ~
train:
  optim_g:
    type: Adam
    lr: 1e-4
  total_iter: 100000
  warmup_iter: -1
  lr_scheme: MultiStepLR
  lr_steps: [50000, 80000]
  lr_gamma: 0.5

  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean

  perceptual_opt:
    type: PerceptualLoss
    layer_weights:
      'conv5_4': 1
    vgg_type: vgg19
    use_input_norm: true
    perceptual_weight: 1.0
    style_weight: 0.05

  lambda_kd_out: 1.0
  lambda_kd_feat: 1.0

val:
  val_freq: 5000
  save_img: true

logger:
  print_freq: 100
  save_checkpoint_freq: 5000

