name: realesrgan_x4plus_siamese_kd
model_type: RealESRGANModelSiamese
scale: 4
num_gpu: 1

datasets:
  train:
    name: RealESRGAN_SiameseTrain
    type: PairedImageDatasetSiamese_basicsr
    dataroot_gt: /datasets/RealESRGAN_data/dataset/train/HR
    dataroot_lq_a: /datasets/RealESRGAN_data/dataset/train/LR_light # ảnh xấu nhẹ -> Teacher
    dataroot_lq_b: /datasets/RealESRGAN_data/dataset/train/LR_moderate  # ảnh xấu nặng -> Student
    io_backend:
      type: disk

    gt_size: 128
    use_flip: true
    use_rot: true
    phase: train

    # Data loader
    use_shuffle: true
    num_worker_per_gpu: 4
    batch_size_per_gpu: 6
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  val:
    name: ValSet
    type: PairedImageDataset
    dataroot_gt: /datasets/RealESRGAN_data/dataset/test/HR
    dataroot_lq: /datasets/RealESRGAN_data/dataset/test/HR_LR_light
    io_backend:
      type: disk

# ----------------- Network -----------------
network_g:
  type: RRDBNet
  num_in_ch: 3
  num_out_ch: 3
  num_feat: 64
  num_block: 23
  num_grow_ch: 32
  scale: 4

# ----------------- Losses -----------------
pixel_loss:
  type: L1Loss
  loss_weight: 1.0
  reduction: mean

kd_loss:
  type: L1Loss
  loss_weight: 1.0
  reduction: mean

lambda_kd: 0.1  # hệ số cho KD loss

# ----------------- Training config -----------------
train:
  optim_g:
    type: Adam
    lr: !!float 2e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [50000, 100000, 200000]
    gamma: 0.5

  total_iter: 300000
  warmup_iter: -1  # no warm up

# ----------------- Validation -----------------
val:
  val_freq: 5000
  save_img: true

# ----------------- Logging -----------------
logger:
  print_freq: 100
  save_checkpoint_freq: 5000
  use_tb_logger: true
  tb_logger_freq: 100

# ----------------- Path -----------------
path:
  pretrain_network_g: /home/namlh/DLEnhance_ImageQuality/Real-ESRGAN/weights/RealESRNet_x4plus.pth  # hoặc để ~ nếu không dùng pretrain
  param_key_g: params_ema
  strict_load_g: true

  resume_state: ~