name: StudentTeacher_RealESRGAN_x4
model_type: StudentTeacherModel
scale: 4
num_gpu: 1
manual_seed: 0

# dataset and data loader settings
datasets:
  train:
    name: StudentTeacherDataset
    type: StudentTeacherDataset
    
    # Paths
    dataroot_gt: /datasets/RealESRGAN_data/dataset/train/HR
    dataroot_lq_student: /datasets/RealESRGAN_data/dataset/train/LR_moderate # Ảnh xấu nhiều cho student
    dataroot_lq_teacher: /datasets/RealESRGAN_data/dataset/train/LR_light     # Ảnh xấu nhẹ cho teacher
    
    filename_tmpl: '{}'
    io_backend:
      type: disk

    gt_size: 256
    use_hflip: true
    use_rot: true

    # data loader
    num_worker_per_gpu: 6
    batch_size_per_gpu: 16
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  val:
    name: Set5
    type: PairedImageDataset
    dataroot_gt: /datasets/RealESRGAN_data/dataset/test/HR
    dataroot_lq: /datasets/RealESRGAN_data/dataset/test/LR_light
    io_backend:
      type: disk

# network structures
network_g:
  type: RRDBNet
  num_in_ch: 3
  num_out_ch: 3
  num_feat: 64
  num_block: 23
  num_grow_ch: 32
  scale: 4

network_teacher:
  type: RRDBNet
  num_in_ch: 3
  num_out_ch: 3
  num_feat: 64
  num_block: 23
  num_grow_ch: 32
  scale: 4

# path
path:
  pretrain_network_g: /home/namlh/DLEnhance_ImageQuality/Real-ESRGAN/weights/RealESRNet_x4plus.pth
  pretrain_network_teacher: ~  # Có thể load pretrained teacher
  param_key_g: params_ema
  param_key_teacher: params_ema
  strict_load_g: true
  strict_load_teacher: true
  resume_state: ~

# training settings
train:
  ema_decay: 0.999
  
  # Student optimizer
  optim_g:
    type: Adam
    lr: !!float 2e-4
    weight_decay: 0
    betas: [0.9, 0.99]
    
  # Teacher optimizer  
  teacher_optim:
    type: Adam
    lr: !!float 2e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  # Student scheduler
  scheduler:
    type: MultiStepLR
    milestones: [50000, 100000, 200000, 300000]
    gamma: 0.5
    
  # Teacher scheduler
  teacher_scheduler:
    type: MultiStepLR
    milestones: [50000, 100000, 200000, 300000]
    gamma: 0.5

  total_iter: 400000
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean
    
  # Distillation loss
  distillation_loss:
    loss_weight: 0.5
    temperature: 4.0
    
  # Feature matching loss
  feature_loss:
    type: MSELoss
    loss_weight: 0.1
    reduction: mean

# validation settings
val:
  val_freq: !!float 5e3
  save_img: false

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 4
      test_y_channel: false

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 1e4
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500