# General settings
name: RealESRGAN_Siamese
model_type: RealESRNetModel
scale: 4
num_gpu: 1
manual_seed: 0

# Dataset settings
dataset:
  train:
    name: DatasetA
    type: PairedImageDataset
    dataroot_gt: /datasets/RealESRGAN_data/dataset/train/HR  # High-resolution images for dataset A
    dataroot_lq: /datasets/RealESRGAN_data/dataset/train/LR_light  # Low-resolution images with light degradation
    io_backend:
      type: disk
    phase: train
    scale: 4
    num_worker_per_gpu: 4
    batch_size_per_gpu: 6
  train_b:
    name: DatasetB
    type: PairedImageDataset
    dataroot_gt: /datasets/RealESRGAN_data/dataset/train/HR  # High-resolution images for dataset B
    dataroot_lq: /datasets/RealESRGAN_data/dataset/train/LR_moderate  # Low-resolution images with heavy degradation
    io_backend:
      type: disk
    phase: train
    scale: 4
    num_worker_per_gpu: 4
    batch_size_per_gpu: 6


# Network settings
network_g:
  type: RRDBNet
  num_in_ch: 3
  num_out_ch: 3
  num_feat: 64
  num_block: 23
  num_grow_ch: 32

# Training settings
train:
  total_iter: 300000
  optim_g:
    type: Adam
    lr: !!float 2e-4
    betas: [0.9, 0.99]
  scheduler:
    type: MultiStepLR
    milestones: [50000, 100000, 200000, 250000]
    gamma: 0.5
  siamese_loss: true  # Optional: Feature alignment between teacher and student
  distillation_loss: true  # L1 loss between teacher and student outputs
  distillation_weight: 0.1  # Weight for distillation loss
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean
  perceptual_opt:
    type: PerceptualLoss
    layer_weights:
      'conv1_2': 0.1
      'conv2_2': 0.1
      'conv3_4': 1
      'conv4_4': 1
      'conv5_4': 1
    loss_weight: 1.0
  gan_opt:
    type: GANLoss
    gan_type: vanilla
    loss_weight: 0.1

# Path settings
path:
  pretrain_network_g: null
  path_teacher: /home/namlh/DLEnhance_ImageQuality/Real-ESRGAN/weights/RealESRNet_x4plus.pth  # Optional: Pretrained teacher weights
  path_student: /home/namlh/DLEnhance_ImageQuality/Real-ESRGAN/weights/RealESRNet_x4plus.pth  # Optional: Pretrained student weights
  root: .
  experiments_root: experiments/RealESRGAN_Siamese
  models: experiments/RealESRGAN_Siamese/models
  training_states: experiments/RealESRGAN_Siamese/training_states
  log: experiments/RealESRGAN_Siamese
  visualization: experiments/RealESRGAN_Siamese/visualization

# Logger settings
logger:
  print_freq: 100
  save_checkpoint_freq: 5000
  use_tb_logger: true