name: RealESRGAN_x4plus_teacher
model:
  type: RealESRGAN
  scale: 4
  num_gpu: 1
  manual_seed: 0
dataset:
  name: LQ_light_GT
  type: PairedImageDataset
  dataroot_gt: /datasets/RealESRGAN_data/dataset/train/HR
  dataroot_lq: /datasets/RealESRGAN_data/dataset/train/LR_light
  filename_tmpl: {}
  io_backend:
    type: disk
  phase: train
  scale: 4
network_g:
  type: RRDBNet
  num_in_ch: 3
  num_out_ch: 3
  num_feat: 64
  num_block: 23
  num_grow_ch: 32
path:
  pretrain_network_g: /home/namlh/DLEnhance_ImageQuality/Real-ESRGAN/weights/RealESRGAN_x4plus.pth
  strict_load_g: true
  resume_state: ~
train:
  optim_g:
    type: Adam
    lr: !!float 2e-4
  scheduler:
    type: MultiStepLR
    milestones: [50000, 100000, 200000, 300000]
    gamma: 0.5
  total_iter: 400000
  warmup_iter: -1
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean
  perceptual_opt:
    type: PerceptualLoss
    layer_weights:
      'conv1_2': 0.1
      'conv2_2': 0.1
      'conv3_4': 1.0
      'conv4_4': 1.0
      'conv5_4': 1.0
    loss_weight: 1.0
  gan_opt:
    type: GANLoss
    gan_type: vanilla
    loss_weight: !!float 1e-1
val:
  name: val
  type: PairedImageDataset
  dataroot_gt: datasets/val/GT
  dataroot_lq: datasets/val/LQ_light
  io_backend:
    type: disk
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3